name: Union API Documentation
title: Union API Documentation
description: Welcome to the official documentation for Union API!
include: ['_pages']
exclude: ['modesta/_pages']
baseurl: ""
url: ""
markdown: kramdown
